### ISSUE TITLE
Change 'Services'

### ISSUE THREAD

**Issue by jgclark** [chineham-repair-cafe/site-production#1]
The thing I'd most like to see changed on the current site is SERVICES  / OUR SERVICES.  It's too professional for what I think we're about.
Please change SERVICES headings → REPAIRS
and OUR SERVICES → WHAT WE REPAIR

**Comment by shymega** [comment]
Just made a PR. I will test it in just a moment. I've mentioned that it might be worth @sibo999 having a look at the changes.. but I'm fairly sure I've covered the scope. The CSS references have also been updated.

**Comment by shymega** [comment]
I've tested it locally, and all works fine. The next step is to wait for Simon to check he's OK with the change, then I'll merge - and push to this repo via the GH Action workflow.
