### ISSUE TITLE
New 'HELPING OUT' section

### ISSUE THREAD

**Issue by jgclark** [chineham-repair-cafe/site-production#5]
We need a clearer 'HELPING OUT or 'GETTING INVOLVED' section, probably before the SUPPORTERS section.
I will add some thoughts later, as its less urgent than the other changes.

**Comment by sibo999** [comment]
If you look at nhrc we have a very simplistic approach 'this could be you'

**Comment by sibo999** [comment]
I've implemented the 'this could be you' approach on the volunteer side of things.

**Comment by sibo999** [comment]
Good in Staging
