### ISSUE TITLE
Meet the Team section.

### ISSUE THREAD

**Issue by shymega** [chineham-repair-cafe/site-production#6]
Currently, commented out on the staging site, is a 'Meet the Team' section. 

I think including photos of every repairer would make the page extremely lengthly. My proposal is that we include the group photo on the header section of the page, at the top, and photos of Trustees and Front of House staff in the 'Meet the Team' section.

Any thoughts on this? Thanks.

**Comment by jgclark** [comment]
I'd keep it simpler, and just have the single team photo in the MEET THE TEAM section. This is nice-to-have info; the priority sections remain those which answer What? When? Where? questions. Then we can have more on the Why? and Who?

**Comment by shymega** [comment]
Can you send the team photo, with the new polo shirts to me? Thanks.

**Comment by sibo999** [comment]
I hostgator staging. I've added in the team photo with the new T shirts on into the team section.

**Comment by sibo999** [comment]
Good in Staging
