### ISSUE TITLE
'Next Cafe' countdown.

### ISSUE THREAD

**Issue by shymega** [chineham-repair-cafe/site-production#8]
Currently, there's a commented-out Javascript function that counts down to the next CRC.

I think we can safely uncomment this at some point.

The backend I'm working on will allow cafes to be scheduled, and the website could neatly call the REST endpoint of the backend to determine the next 'CHI' (Chineham) cafe date, and if it's running.

However, for simplicity, we may prefer to keep the Javascript function as-is. The benefit of using the backend is that it'll be linked in with the ticket system.

**Comment by sibo999** [comment]
Lets get the code uncommented on staging and working. 
One for you Dom

**Comment by shymega** [comment]
Sure, that's assigned to me. I'm uploading from staging to Git once I pull FTP.

**Comment by shymega** [comment]
I've uncommented the timer, can you see it on staging @sibo999? I can't yet.

**Comment by sibo999** [comment]
No sorry can’t see it. Might be a div issue.

Its on live but the wrong colour!

**Comment by sibo999** [comment]
Hi Dom

I’ve sorted out the font colour on the timer on staging. 

Do you want to move to live?

 

Regards

Simon

**Comment by shymega** [comment]
Fixed, with dynamic month prediction.
